[package]
name = "js"
version = "0.1.0"
edition = "2024"

[dependencies]
eq-float = "0.1.0"

[dev-dependencies]
rstest = "0.26.1"

[lints.clippy]
# cargo = "warn"
# nursery = "warn"
# pedantic = "warn"

[lints.rust]
future-incompatible = "deny"
keyword-idents = "deny"
nonstandard-style = "deny"
dead-code = "allow"
